import type { Investigation } from './investigation-types';

const baseTrace = (traceId: string, caseId: string) => [
  { trace_id: traceId, call_id: `${caseId}-request`, sequence: 1, event_type: 'request_received', timestamp: '2026-09-06T12:42:03-03:00', summary: 'Solicitação técnica do cliente recebida e delimitada.' },
  { trace_id: traceId, call_id: `${caseId}-understanding`, sequence: 2, event_type: 'understanding_completed', timestamp: '2026-09-06T12:42:04-03:00', duration_ms: 684, summary: 'Solicitação classificada e entidades extraídas.' },
  { trace_id: traceId, call_id: `${caseId}-planner`, sequence: 3, event_type: 'planner_completed', timestamp: '2026-09-06T12:42:05-03:00', duration_ms: 811, summary: 'Plano de investigação somente-leitura criado.' },
];

export const investigations: Investigation[] = [
  {
    case_id: 'CASE-2026-0418', request_id: 'REQ-8C21', trace_id: 'trace_0418', asset_id: 'asset_C710', asset_name: 'Compressor C-710', company: 'Petro Delta',
    request: 'O RMS do compressor subiu nas últimas duas semanas, mas nenhum insight foi emitido. Precisamos entender o motivo.',
    request_class: 'investigate', entities: ['asset_C710', 'RMS', 'insight'], investigation_targets: ['Validar o contexto do ativo', 'Inspecionar o comportamento do RMS', 'Verificar a qualidade dos dados e o histórico de insights'], missing_information: [],
    plan_objectives: ['Confirmar o ativo monitorado e a conectividade atual.', 'Comparar as leituras recentes de RMS com o contexto operacional disponível.', 'Verificar se a evidência sustenta a ausência de um insight.'],
    planned_capabilities: ['get_asset_context', 'get_asset_rms', 'get_asset_insights'], started_at: '06 set 2026 · 12:42', duration: '8,4 s', terminal_state: 'GROUNDED_COMPLETION', evidence_quality: 'HIGH',
    evidence_quality_reasons: ['3 de 3 afirmações fundamentadas', '3 evidências completas', '0 conflitos ou fontes indisponíveis', 'Rastreabilidade completa até a fonte'], unresolved_points: [],
    trace: [
      ...baseTrace('trace_0418', '0418'),
      { trace_id: 'trace_0418', call_id: 'call_context_0418', sequence: 4, event_type: 'tool_requested', timestamp: '2026-09-06T12:42:06-03:00', tool_name: 'get_asset_context', summary: 'O investigador solicitou o contexto do ativo.' },
      { trace_id: 'trace_0418', call_id: 'call_context_0418', sequence: 5, event_type: 'tool_completed', timestamp: '2026-09-06T12:42:07-03:00', tool_name: 'get_asset_context', duration_ms: 420, summary: 'Contexto do ativo retornado com estado semântico completo.', details: { status_code: 200, evidence_status: 'complete' } },
      { trace_id: 'trace_0418', call_id: 'call_rms_0418', sequence: 6, event_type: 'tool_completed', timestamp: '2026-09-06T12:42:08-03:00', tool_name: 'get_asset_rms', duration_ms: 532, summary: 'Série recente de RMS retornada e validada.', details: { status_code: 200, evidence_status: 'complete' } },
      { trace_id: 'trace_0418', call_id: 'call_insights_0418', sequence: 7, event_type: 'tool_completed', timestamp: '2026-09-06T12:42:09-03:00', tool_name: 'get_asset_insights', duration_ms: 618, summary: 'Histórico de insights retornado sem diagnóstico ativo.', details: { status_code: 200, evidence_status: 'complete' } },
      { trace_id: 'trace_0418', call_id: 'conclusion_0418', sequence: 8, event_type: 'conclusion_created', timestamp: '2026-09-06T12:42:10-03:00', summary: 'Conclusão fundamentada criada a partir de três evidências.' },
      { trace_id: 'trace_0418', call_id: 'report_0418', sequence: 9, event_type: 'reporter_completed', timestamp: '2026-09-06T12:42:11-03:00', duration_ms: 904, summary: 'Relatório técnico preparado para a Equipe de Engenharia TRACTIAN.' },
      { trace_id: 'trace_0418', call_id: 'terminal_0418', sequence: 10, event_type: 'terminal_state_reached', timestamp: '2026-09-06T12:42:11-03:00', summary: 'Encerrado com conclusão fundamentada.' },
    ],
    evidence: [
      { evidence_id: 'E-0418-01', trace_id: 'trace_0418', source_call_id: 'call_context_0418', source_trace_sequence: 5, sequence: 1, collected_at: '2026-09-06T12:42:07-03:00', tool_name: 'get_asset_context', client_operation: 'get_asset', arguments: { asset_id: 'asset_C710' }, evidence_status: 'complete', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_C710', summary: 'O compressor C-710 está online, monitorado e vinculado à empresa esperada.', source: 'API TRACTIAN · Contexto do ativo' },
      { evidence_id: 'E-0418-02', trace_id: 'trace_0418', source_call_id: 'call_rms_0418', source_trace_sequence: 6, sequence: 2, collected_at: '2026-09-06T12:42:08-03:00', tool_name: 'get_asset_rms', client_operation: 'get_asset_rms', arguments: { asset_id: 'asset_C710' }, evidence_status: 'complete', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_C710/rms', summary: 'O RMS subiu de 2,8 mm/s para 4,2 mm/s nas leituras expostas pela API.', notes: 'O endpoint expõe a série recente disponível; nenhuma janela de tempo arbitrária foi solicitada.', source: 'API TRACTIAN · Leituras de RMS' },
      { evidence_id: 'E-0418-03', trace_id: 'trace_0418', source_call_id: 'call_insights_0418', source_trace_sequence: 7, sequence: 3, collected_at: '2026-09-06T12:42:09-03:00', tool_name: 'get_asset_insights', client_operation: 'list_asset_insights', arguments: { asset_id: 'asset_C710' }, evidence_status: 'complete', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_C710/insights', summary: 'Nenhum insight diagnóstico ativo estava presente para o ativo no momento da coleta.', source: 'API TRACTIAN · Histórico de insights' },
    ],
    claims: [
      { claim_id: 'CL-0418-01', statement: 'O compressor monitorado está online e corretamente associado ao ativo solicitado.', supporting_evidence_ids: ['E-0418-01'], contradictory_evidence_ids: [], status: 'supported' },
      { claim_id: 'CL-0418-02', statement: 'As leituras de RMS disponíveis mostram elevação de 2,8 mm/s para 4,2 mm/s.', supporting_evidence_ids: ['E-0418-02'], contradictory_evidence_ids: [], status: 'supported' },
      { claim_id: 'CL-0418-03', statement: 'Nenhum insight diagnóstico ativo foi retornado no momento da investigação.', supporting_evidence_ids: ['E-0418-03'], contradictory_evidence_ids: [], limitation: 'A investigação não infere o limiar interno do modelo nem lógica de decisão não publicada.', status: 'qualified' },
    ],
    report: { report_id: 'RPT-0418', audience: 'tractian_engineering_team', executive_summary: 'O ativo está online e as leituras de RMS expostas estão subindo, enquanto o endpoint de insights não retornou diagnóstico ativo. A evidência sustenta a verificação do pipeline de geração de insights, sem afirmar um limiar não publicado.', investigation_performed: ['Validou o contexto do ativo e o estado de monitoramento.', 'Inspecionou os dados de RMS expostos pela API.', 'Consultou o histórico de insights do ativo.'], findings: ['A identidade e a conectividade do ativo são consistentes.', 'O RMS recente disponível subiu.', 'Nenhum insight diagnóstico ativo foi retornado.'], evidence_references: ['E-0418-01', 'E-0418-02', 'E-0418-03'], limitations: ['A API não expõe o limiar interno do modelo nem o rastro de inferência.'], missing_information: [], suggested_engineer_next_steps: ['Revisar a telemetria de geração de insights do asset_C710 no entorno das últimas leituras de RMS.'] },
    mock: true,
  },
  {
    case_id: 'CASE-2026-0419', request_id: 'REQ-8C39', trace_id: 'trace_0419', asset_id: 'asset_M205', asset_name: 'Motor M-205', company: 'Cimento Vale',
    request: 'O sistema indicou desalinhamento, mas o relatório do especialista aponta base solta. Qual diagnóstico devemos considerar?', request_class: 'investigate', entities: ['asset_M205', 'desalinhamento', 'base solta'], investigation_targets: ['Comparar os diagnósticos disponíveis', 'Inspecionar a evidência de sustentação', 'Identificar o conflito não resolvido'], missing_information: [],
    plan_objectives: ['Validar o contexto do ativo.', 'Obter o insight automático e a análise do especialista disponível.', 'Determinar se a evidência resolve os diagnósticos conflitantes.'], planned_capabilities: ['get_asset_context', 'get_asset_insights', 'get_asset_report'], started_at: '06 set 2026 · 12:18', duration: '11,2 s', terminal_state: 'SAFE_ESCALATION', evidence_quality: 'LOW',
    evidence_quality_reasons: ['1 evidência completa e 1 inconclusiva', 'Diagnósticos conflitantes seguem não resolvidos', 'Nenhuma conclusão fundamentada segura', 'Rastreabilidade preservada para continuação humana'], unresolved_points: ['O diagnóstico automático e o do especialista não podem ser reconciliados com os dados hoje expostos.'],
    trace: [
      ...baseTrace('trace_0419', '0419'),
      { trace_id: 'trace_0419', call_id: 'call_context_0419', sequence: 4, event_type: 'tool_completed', timestamp: '2026-09-06T12:18:06-03:00', tool_name: 'get_asset_context', duration_ms: 398, summary: 'Contexto do ativo confirmado.', details: { status_code: 200, evidence_status: 'complete' } },
      { trace_id: 'trace_0419', call_id: 'call_report_0419', sequence: 5, event_type: 'tool_completed', timestamp: '2026-09-06T12:18:08-03:00', tool_name: 'get_asset_report', duration_ms: 721, summary: 'A referência ao relatório do especialista voltou sem medições diagnósticas suficientes.', details: { status_code: 200, evidence_status: 'inconclusive' } },
      { trace_id: 'trace_0419', call_id: 'evidence_0419', sequence: 6, event_type: 'evidence_created', timestamp: '2026-09-06T12:18:08-03:00', summary: 'Evidência inconclusiva registrada sem normalização.' },
      { trace_id: 'trace_0419', call_id: 'terminal_0419', sequence: 7, event_type: 'terminal_state_reached', timestamp: '2026-09-06T12:18:11-03:00', summary: 'Encaminhado para revisão; decisão humana necessária.' },
    ],
    evidence: [
      { evidence_id: 'E-0419-01', trace_id: 'trace_0419', source_call_id: 'call_context_0419', source_trace_sequence: 4, sequence: 1, collected_at: '2026-09-06T12:18:06-03:00', tool_name: 'get_asset_context', client_operation: 'get_asset', arguments: { asset_id: 'asset_M205' }, evidence_status: 'complete', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_M205', summary: 'O motor solicitado e o contexto de monitoramento foram confirmados.', source: 'API TRACTIAN · Contexto do ativo' },
      { evidence_id: 'E-0419-02', trace_id: 'trace_0419', source_call_id: 'call_report_0419', source_trace_sequence: 5, sequence: 2, collected_at: '2026-09-06T12:18:08-03:00', tool_name: 'get_asset_report', client_operation: 'get_asset_report', arguments: { asset_id: 'asset_M205' }, evidence_status: 'inconclusive', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_M205/report', summary: 'O relatório aponta base solta, mas a resposta exposta não traz as medições necessárias para reconciliar com o diagnóstico automático de desalinhamento.', notes: 'O transporte HTTP teve sucesso; a evidência semântica permanece inconclusiva.', source: 'API TRACTIAN · Relatório do especialista' },
    ],
    claims: [], human_handoff: { handoff_id: 'HO-0419', reason_codes: ['CONFLICTING_DIAGNOSES', 'INSUFFICIENT_DIAGNOSTIC_DETAIL'], evidence_ids: ['E-0419-01', 'E-0419-02'], missing_information: ['Espectro de vibração validado ou resultado de inspeção física'], suggested_next_step: 'Comparar o espectro com a inspeção do especialista e verificar a fixação da base antes de escolher um diagnóstico.' }, mock: true,
  },
  {
    case_id: 'CASE-2026-0420', request_id: 'REQ-8C44', trace_id: 'trace_0420', asset_id: 'asset_unknown', asset_name: 'Ativo não identificado', company: 'Papel Sul',
    request: 'Preciso entender por que a máquina da linha dois parou de gerar dados ontem.', request_class: 'unclear', entities: ['máquina da linha dois', 'interrupção de dados'], investigation_targets: ['Identificar o ativo solicitado antes de consultar telemetria'], missing_information: ['Identificador exato do ativo'], plan_objectives: ['Resolver a identidade do ativo antes de qualquer consulta de leitura.'], planned_capabilities: [], started_at: '06 set 2026 · 11:56', duration: '1,7 s', terminal_state: 'AWAITING_REQUIRED_INFORMATION', evidence_quality: 'INSUFFICIENT EVIDENCE',
    evidence_quality_reasons: ['0 evidências registradas', 'Falta a identidade do ativo', 'Nenhuma consulta feita com identificador adivinhado', 'Nenhuma conclusão inventada'], unresolved_points: ['Qual ativo da linha dois está afetado?'],
    trace: [
      ...baseTrace('trace_0420', '0420').slice(0, 2),
      { trace_id: 'trace_0420', call_id: 'decision_0420', sequence: 3, event_type: 'decision_accepted', timestamp: '2026-09-06T11:56:05-03:00', summary: 'Pergunta ao solicitante aceita porque a identidade do ativo é obrigatória.' },
      { trace_id: 'trace_0420', call_id: 'terminal_0420', sequence: 4, event_type: 'terminal_state_reached', timestamp: '2026-09-06T11:56:05-03:00', summary: 'Encerrado aguardando informações, sem executar nenhuma consulta.' },
    ], evidence: [], claims: [], mock: true,
  },
  {
    case_id: 'CASE-2026-0417', request_id: 'REQ-8B04', trace_id: 'trace_0417', asset_id: 'asset_M312', asset_name: 'Motor do refiner M-312', company: 'Papel Sul',
    request: 'A análise do refiner ficou desatualizada depois da manutenção. Podemos confiar no baseline atual?',
    request_class: 'investigate', entities: ['asset_M312', 'baseline', 'manutenção'], investigation_targets: ['Contexto do ativo', 'Estado da linha de base', 'Comparação de espectro'], missing_information: [],
    plan_objectives: ['Confirmar o ativo e o estado atual do sensor.', 'Verificar se a manutenção invalidou a linha de base.', 'Comparar o comportamento do espectro com a linha de base armazenada.'],
    planned_capabilities: ['get_asset_context', 'get_asset_baseline', 'get_asset_spectrum'], started_at: '06 set 2026 · 11:18', duration: '12,6 s', terminal_state: 'SAFE_ESCALATION', evidence_quality: 'MEDIUM',
    evidence_quality_reasons: ['2 evidências completas', '1 linha de base parcial', '1 espectro indisponível', 'Rastreabilidade completa nos registros coletados'],
    unresolved_points: ['O endpoint de espectro estava indisponível, então a comparação de frequência não pôde ser concluída.'],
    trace: [
      ...baseTrace('trace_0417', '0417'),
      { trace_id: 'trace_0417', call_id: 'call_ctx_0417', sequence: 4, event_type: 'tool_completed', timestamp: '2026-09-06T11:18:44-03:00', tool_name: 'get_asset_context', duration_ms: 388, summary: 'Contexto do ativo retornado com estado semântico completo.', details: { status_code: 200, evidence_status: 'complete' } },
      { trace_id: 'trace_0417', call_id: 'call_base_0417', sequence: 5, event_type: 'tool_completed', timestamp: '2026-09-06T11:18:46-03:00', tool_name: 'get_asset_baseline', duration_ms: 741, summary: 'A linha de base retornou dados parciais após a manutenção.', details: { status_code: 200, evidence_status: 'partial' } },
      { trace_id: 'trace_0417', call_id: 'call_spec_0417', sequence: 6, event_type: 'tool_completed', timestamp: '2026-09-06T11:18:49-03:00', tool_name: 'get_asset_spectrum', duration_ms: 2140, summary: 'O endpoint de espectro reportou o recurso como indisponível.', details: { status_code: 200, evidence_status: 'unavailable' } },
      { trace_id: 'trace_0417', call_id: 'terminal_0417', sequence: 7, event_type: 'terminal_state_reached', timestamp: '2026-09-06T11:18:52-03:00', summary: 'Encaminhado para revisão: a evidência não sustenta uma conclusão.' },
    ],
    evidence: [
      { evidence_id: 'E-0417-01', trace_id: 'trace_0417', source_call_id: 'call_ctx_0417', source_trace_sequence: 4, sequence: 1, collected_at: '2026-09-06T11:18:44-03:00', tool_name: 'get_asset_context', client_operation: 'get_asset', arguments: { asset_id: 'asset_M312' }, evidence_status: 'complete', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_M312', summary: 'O motor do refiner M-312 está online e monitorado.', source: 'API TRACTIAN · Contexto do ativo' },
      { evidence_id: 'E-0417-02', trace_id: 'trace_0417', source_call_id: 'call_base_0417', source_trace_sequence: 5, sequence: 2, collected_at: '2026-09-06T11:18:46-03:00', tool_name: 'get_asset_baseline', client_operation: 'get_baseline', arguments: { asset_id: 'asset_M312' }, evidence_status: 'partial', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_M312/baseline', summary: 'A linha de base voltou sem o bloco de características.', notes: 'Resposta parcial: os campos de comparação de características não vieram.', source: 'API TRACTIAN · Linha de base' },
      { evidence_id: 'E-0417-03', trace_id: 'trace_0417', source_call_id: 'call_spec_0417', source_trace_sequence: 6, sequence: 3, collected_at: '2026-09-06T11:18:49-03:00', tool_name: 'get_asset_spectrum', client_operation: 'get_spectrum', arguments: { asset_id: 'asset_M312' }, evidence_status: 'unavailable', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_M312/spectrum', summary: 'O espectro não pôde ser obtido no momento da coleta.', source: 'API TRACTIAN · Espectro de vibração' },
    ],
    claims: [],
    mock: true,
  },
  {
    case_id: 'CASE-2026-0416', request_id: 'REQ-8A77', trace_id: 'trace_0416', asset_id: 'asset_S425', asset_name: 'Spindle secundário S-425', company: 'ACME',
    request: 'Confirme o cadastro atual do spindle S-425 e o status do sensor desde o último turno.',
    request_class: 'contextualize', entities: ['asset_S425'], investigation_targets: ['Contexto do ativo'], missing_information: [],
    plan_objectives: ['Obter o cadastro atual do ativo.', 'Reportar o estado registrado do sensor.'],
    planned_capabilities: ['get_asset_context'], started_at: '05 set 2026 · 17:40', duration: '6,1 s', terminal_state: 'GROUNDED_COMPLETION', evidence_quality: 'HIGH',
    evidence_quality_reasons: ['1 de 1 afirmação fundamentada', '1 evidência completa', '0 conflitos', 'Rastreabilidade completa até a fonte'],
    unresolved_points: ['A solicitação pedia uma janela por turno, que nenhuma ferramenta de leitura consegue expressar.'],
    trace: [
      ...baseTrace('trace_0416', '0416'),
      { trace_id: 'trace_0416', call_id: 'call_ctx_0416', sequence: 4, event_type: 'tool_requested', timestamp: '2026-09-05T17:41:04-03:00', tool_name: 'get_asset_context', summary: 'O investigador solicitou o cadastro do ativo.', details: { rejected_argument: 'shift' } },
      { trace_id: 'trace_0416', call_id: 'call_ctx_0416', sequence: 5, event_type: 'tool_completed', timestamp: '2026-09-05T17:41:06-03:00', tool_name: 'get_asset_context', duration_ms: 402, summary: 'Cadastro do ativo retornado com estado semântico completo.', details: { status_code: 200, evidence_status: 'complete' } },
      { trace_id: 'trace_0416', call_id: 'conclusion_0416', sequence: 6, event_type: 'conclusion_created', timestamp: '2026-09-05T17:41:07-03:00', summary: 'Conclusão fundamentada criada a partir do cadastro do ativo.' },
      { trace_id: 'trace_0416', call_id: 'report_0416', sequence: 7, event_type: 'reporter_completed', timestamp: '2026-09-05T17:41:08-03:00', duration_ms: 812, summary: 'Relatório técnico preparado para a Equipe de Engenharia TRACTIAN.' },
      { trace_id: 'trace_0416', call_id: 'terminal_0416', sequence: 8, event_type: 'terminal_state_reached', timestamp: '2026-09-05T17:41:09-03:00', summary: 'Encerrado com conclusão fundamentada.' },
    ],
    evidence: [
      { evidence_id: 'E-0416-01', trace_id: 'trace_0416', source_call_id: 'call_ctx_0416', source_trace_sequence: 5, sequence: 1, collected_at: '2026-09-05T17:41:06-03:00', tool_name: 'get_asset_context', client_operation: 'get_asset', arguments: { asset_id: 'asset_S425' }, evidence_status: 'complete', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_S425', summary: 'Spindle secundário, machine type spindle, criticality medium, sensor online.', source: 'API TRACTIAN · Contexto do ativo' },
    ],
    claims: [
      { claim_id: 'claim_asset_S425', statement: 'O ativo asset_S425 é um Spindle secundário, do tipo spindle, com criticidade média e sensor online.', supporting_evidence_ids: ['E-0416-01'], contradictory_evidence_ids: [], status: 'supported' },
    ],
    report: {
      report_id: 'RPT-0416', audience: 'tractian_engineering_team',
      executive_summary: 'O cadastro registrado do S-425 foi obtido e reportado sem inferência. A janela por turno solicitada não pôde ser aplicada.',
      investigation_performed: ['Obteve o cadastro atual do ativo por uma capacidade somente-leitura.'],
      findings: ['O ativo asset_S425 é um Spindle secundário, do tipo spindle, com criticidade média e sensor online.'],
      evidence_references: ['E-0416-01'],
      limitations: ['Nenhuma capacidade de leitura expõe janela de tempo por turno, então a parte temporal da solicitação não foi respondida.'],
      missing_information: [],
      suggested_engineer_next_steps: ['Decidir se leituras por turno devem ser adicionadas à superfície de ferramentas.'],
    },
    mock: true,
  },
  {
    case_id: 'CASE-2026-0415', request_id: 'REQ-89F2', trace_id: 'trace_0415', asset_id: 'asset_B211', asset_name: 'Bomba de refrigerante B-211', company: 'Aurora',
    request: 'Resuma o estado da análise atual da bomba B-211 para a equipe de engenharia.',
    request_class: 'investigate', entities: ['asset_B211'], investigation_targets: ['Contexto do ativo', 'Estado da análise'], missing_information: [],
    plan_objectives: ['Obter o cadastro do ativo.', 'Listar as análises vinculadas ao ativo.', 'Resumir a análise atual para a engenharia.'],
    planned_capabilities: ['get_asset_context', 'list_asset_analyses', 'get_analysis_details'], started_at: '05 set 2026 · 09:27', duration: '9,8 s', terminal_state: 'FAILED', evidence_quality: 'INSUFFICIENT EVIDENCE',
    evidence_quality_reasons: ['2 evidências completas coletadas', 'O relatório introduziu uma afirmação que a conclusão nunca produziu', 'A validação determinística bloqueou o relatório'],
    unresolved_points: ['O relatório não pode ser liberado enquanto a afirmação inventada não for removida.'],
    trace: [
      ...baseTrace('trace_0415', '0415'),
      { trace_id: 'trace_0415', call_id: 'call_ctx_0415', sequence: 4, event_type: 'tool_completed', timestamp: '2026-09-05T09:27:39-03:00', tool_name: 'get_asset_context', duration_ms: 355, summary: 'Cadastro do ativo retornado com estado semântico completo.', details: { status_code: 200, evidence_status: 'complete' } },
      { trace_id: 'trace_0415', call_id: 'call_an_0415', sequence: 5, event_type: 'tool_completed', timestamp: '2026-09-05T09:27:41-03:00', tool_name: 'get_analysis_details', duration_ms: 604, summary: 'Detalhes da análise retornados com estado semântico completo.', details: { status_code: 200, evidence_status: 'complete' } },
      { trace_id: 'trace_0415', call_id: 'conclusion_0415', sequence: 6, event_type: 'conclusion_created', timestamp: '2026-09-05T09:27:42-03:00', summary: 'Conclusão fundamentada criada com duas afirmações.' },
      { trace_id: 'trace_0415', call_id: 'report_0415', sequence: 7, event_type: 'reporter_failed', timestamp: '2026-09-05T09:27:44-03:00', summary: 'Relatório rejeitado: continha um identificador de afirmação ausente da conclusão.', details: { violations: 'REPORTER_FABRICATED_CLAIM' } },
      { trace_id: 'trace_0415', call_id: 'terminal_0415', sequence: 8, event_type: 'terminal_state_reached', timestamp: '2026-09-05T09:27:44-03:00', summary: 'Falhou: relatório bloqueado antes da publicação.' },
    ],
    evidence: [
      { evidence_id: 'E-0415-01', trace_id: 'trace_0415', source_call_id: 'call_ctx_0415', source_trace_sequence: 4, sequence: 1, collected_at: '2026-09-05T09:27:39-03:00', tool_name: 'get_asset_context', client_operation: 'get_asset', arguments: { asset_id: 'asset_B211' }, evidence_status: 'complete', transport_ok: true, status_code: 200, method: 'GET', path: '/assets/asset_B211', summary: 'Bomba de refrigerante, machine type pump, criticality medium, sensor degraded.', source: 'API TRACTIAN · Contexto do ativo' },
      { evidence_id: 'E-0415-02', trace_id: 'trace_0415', source_call_id: 'call_an_0415', source_trace_sequence: 5, sequence: 2, collected_at: '2026-09-05T09:27:41-03:00', tool_name: 'get_analysis_details', client_operation: 'get_analysis', arguments: { analysis_id: 'an_9906' }, evidence_status: 'complete', transport_ok: true, status_code: 200, method: 'GET', path: '/analyses/an_9906', summary: 'A análise an_9906 está desatualizada: falha de rolamento, severidade alta, confiança 0,75.', source: 'API TRACTIAN · Análise' },
    ],
    claims: [
      { claim_id: 'claim_asset_B211', statement: 'O ativo asset_B211 é uma Bomba de refrigerante, do tipo bomba, com criticidade média e sensor em estado degradado.', supporting_evidence_ids: ['E-0415-01'], contradictory_evidence_ids: [], status: 'supported' },
      { claim_id: 'claim_an_9906', statement: 'A análise an_9906 está desatualizada, do tipo falha de rolamento, com severidade alta e confiança 0,75.', supporting_evidence_ids: ['E-0415-02'], contradictory_evidence_ids: [], status: 'supported' },
    ],
    mock: true,
  },
];
